# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:



 
  build:
    runs-on: windows-latest
    
    services:
      postgres:
          # Docker Hub image
          image: postgres:12

          # Provide the password for postgres
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: simple_bank
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5  
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'


    - name: Set up Scoop  
      run: |  
        # Use [[ character to avoid errors if Scoop is already installed  
        [ -d "$env:USERPROFILE\scoop" ] || powershell -Command "Set-ExecutionPolicy RemoteSigned -scope CurrentUser"  
        [ -d "$env:USERPROFILE\scoop" ] || powershell -Command "iwr -useb get.scoop.sh | iex"  

    - name: install migrate
      run: |  
        $env:Path += ";$env:USERPROFILE\scoop\shims"  
        scoop install migrate 
    
    - name:  migrate up 
      run: migrate -path db/migration -database "postgresql://root:mysecretpassword@localhost:5432/simple_bank?sslmode=disable" -verbose up
    

    - name: Test
      run: go test -v ./...
